// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://woorkbznpjiczkpmiack.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indvb3JrYnpucGppY3prcG1pYWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTA1OTIsImV4cCI6MjA2NTQ2NjU5Mn0.fyqNqYZ5szX_uWtwqpG0-D24-pWaALwLRiXX6BopjxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);